### ISSUE TITLE
nix run payment issue

### ISSUE THREAD

**Issue by smunx** [tweag/hello-plutarch#24]
**Describe the bug**
error (ignored): error: unable to download 'https://public-plutonomicon.cachix.org/72gbka951b0r3y3facwwi3cwzy2br080.narinfo': HTTP error 402
response body:
Payment Required: https://app.cachix.org/billing
error (ignored): error: unable to download 'https://public-plutonomicon.cachix.org/927f1x17xk81fqfpzlbxpy870z3164cy.narinfo': HTTP error 402

**To Reproduce**
nix run

**Comment by Niols** [comment]
Thank you for reporting this! Indeed, the Plutonomicon Cachix has been discontinued from lack of payment by the maintainers. cf https://github.com/tweag/hello-plutarch/pull/25 that removes it from our flake. Sadly, this might lead to a bigger compilation time for the Nix environment.

**Comment by Niols** [comment]
#25 has now been merged, so the latest flake on `main` does not use the Plutonomicon Cachix anymore. This might lead to bigger compilation times, but sadly I don't have a better solution than to wait for MLabs to maybe revive that Nix cache. In the meantime, I'll close the issue. Feel free to reopen if you still encounter an issue!
